### ISSUE TITLE
Account maintenance: Forgot Userid/Change Password

### ISSUE THREAD

**Issue by MattTW** [MattDahEpic/ha-midas#15]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/MattDahEpic/ha-midas/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When setting up a new Midas account, the dialog text emphasizes that the password cannot be changed after creating it.

### Describe the solution you'd like

I did find links as part of the Midas web console (https://midasweb.energy.ca.gov/Login) that do work:

https://midasweb.energy.ca.gov/Pages/AccountMaint/ForgotUsername
https://midasweb.energy.ca.gov/Pages/AccountMaint/ForgotPassword

I did try these, they both work, you provide the email you registered with:  Forgot username will email you your username, forgot password will send you a link allowing you to reset your password.

### Describe alternatives you've considered

Could provide links to these in the dialog or documentation.  Or provide custom dialogs as part of the integration to perform these actions.  Maybe not needed enough to provide anything but links in doc.

### Additional context

Thank you for creating this Midas integration, so useful!

**Comment by MattDahEpic** [comment]
Well would you look at that! I'll go ahead and update the login dialog strings and add these links to the documentation and the reauthenticate dialog

**Comment by MattDahEpic** [comment]
This will be available in version 0.2.1 shortly
