### ISSUE TITLE
Allow changing RINs after setup

### ISSUE THREAD

**Issue by Particpant** [MattDahEpic/ha-midas#5]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/MattDahEpic/ha-midas/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

It's possible/probable that my RIN will likely change over time for any reason, however the H-A energy dashboard doesn't seem to like having concurrent sources for pricing (or consumption/generation) set up, I believe this means there'll be data loss if I update to a new entity in the energy dashboard.

### Describe the solution you'd like

It'd be nice if I could edit an existing integration to change the target RIN

### Describe alternatives you've considered

A template to use in the energy dashboard. I think I need to do this anyhow to sum the cost of two RINs.
It might be worth mentioning to users that this is best used via template for anyone, though for the reasons above, if it's not feasible to edit the already-created devices.

### Additional context

Thanks for the cool integration!

**Comment by MattDahEpic** [comment]
This feature is included in version 0.1.3, simply use the Reconfigure feature to access the rate list again.
![image](https://github.com/user-attachments/assets/e35af8be-228a-47b2-83c8-c2ca210595f1)

I've also updated the README with notes recommending using a helper.
Thank you for your feedback!

**Comment by Particpant** [comment]
Thank you!
