### ISSUE TITLE
Expose rate name as an entity instead of an attribute on an entity.

### ISSUE THREAD

**Issue by Particpant** [MattDahEpic/ha-midas#7]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/MattDahEpic/ha-midas/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'd like to expose the current rate name in my HA UI. That's not always easy to do for _attributes_ of an entity. I'd also like to drive automation based on the current rate _name_.

### Describe the solution you'd like

I'd like to see the rate names (previous, current, and next) as entities.

### Describe alternatives you've considered

Template helpers, maybe?
Entities for just current/next? HA's recorder/history should have all the look back someone might need, I think.
I think the current "standard" in HA is to have fewer attributes per entity, unless I've misunderstood.

### Additional context

N/A

**Comment by Particpant** [comment]
I appreciate your work to build this out as it currently exists!

**Comment by MattDahEpic** [comment]
Just confirming here, you're looking for *tariff* name not the rate name? Given your use cases it sounds like the tariff is the right one
![image](https://github.com/user-attachments/assets/fd9a6869-79a4-4ad1-be91-7b5c515bf5f8)

**Comment by Particpant** [comment]
Yes, sorry for the mistaken terminology, I'd be looking for the Tariff Name.

**Comment by MattDahEpic** [comment]
This will be added in the next version as a disabled-by-default entity so as to not clutter people's databases
![image](https://github.com/user-attachments/assets/3426eb5b-5250-4a33-92c2-98d2dc9dd971)
